final messages = [
  {'country': 'India', 'player': 'Salah'},
  {'country': 'India', 'player': 'Rohit'},
  {'country': 'Australia', 'player': 'Warner'},
  {'country': 'west indies', 'player': 'pollard'},
  {'country': 'West indies', 'player': 'Gayle'},
  {'country': 'Sri Lanka', 'player': 'Mathews'},
  {'country': 'India', 'player': 'Takur'},
  {'country': 'India', 'player': 'Virat'},
  {'country': 'Australia', 'player': 'Kawaja'},
  {'country': 'west indies', 'player': 'Bravo'},
  {'country': 'West indies', 'player': 'Brathwaite'},
  {'country': 'Sri Lanka', 'player': 'Thirimanne'},
  {'country': 'India', 'player': 'Ashwin'},
  {'country': 'India', 'player': 'Rohit'},
  {'country': 'Australia', 'player': 'Smith'},
  {'country': 'west indies', 'player': 'pollard'},
  {'country': 'West indies', 'player': 'Gayle'},
  {'country': 'Sri Lanka', 'player': 'Herath'},
  {'country': 'India', 'player': 'Hardik'},
  {'country': 'India', 'player': 'Jaddu'},
  {'country': 'Australia', 'player': 'Finch'},
  {'country': 'west indies', 'player': 'Russell'},
  {'country': 'West indies', 'player': 'Narine'},
  {'country': 'Sri Lanka', 'player': 'Lakmal'},
];
